name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Git
        run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"

      - name: Rename folder
        run: |
          mv lang Localizations
          git add .
          git commit -m "rename lang folder to localizations folder"
          git push origin

      - name: Make .bundle files
        run: |
          mkdir -p Bundles
          cd Bundles
          ln -s ../Tweaks/DontEatMyContent/layout/Library/Application\ Support/DontEatMyContent.bundle DontEatMyContent.bundle
          ln -s ../Tweaks/Return-YouTube-Dislikes/layout/Library/Application\ Support/RYD.bundle RYD.bundle
          ln -s ../Tweaks/YTABConfig/layout/Library/Application\ Support/YTABC.bundle YTABC.bundle
          ln -s ../Tweaks/YTHoldForSpeed/layout/Library/Application\ Support/YTHoldForSpeed.bundle YTHoldForSpeed.bundle
          ln -s ../Tweaks/YTUHD/layout/Library/Application\ Support/YTUHD.bundle YTUHD.bundle
          ln -s ../Tweaks/YTVideoOverlay/layout/Library/Application\ Support/YTVideoOverlay.bundle YTVideoOverlay.bundle
          ln -s ../Tweaks/YouGroupSettings/layout/Library/Application\ Support/YouGroupSettings.bundle YouGroupSettings.bundle
          ln -s ../Tweaks/YouMute/layout/Library/Application\ Support/YouMute.bundle YouMute.bundle
          ln -s ../Tweaks/YouPiP/layout/Library/Application\ Support/YouPiP.bundle YouPiP.bundle
          ln -s ../Tweaks/YouQuality/layout/Library/Application\ Support/YouQuality.bundle YouQuality.bundle
          ln -s ../Tweaks/iSponsorBlock/layout/Library/Application\ Support/iSponsorBlock.bundle iSponsorBlock.bundle
          ln -s ../Localizations/YouTubeRebornPlus.bundle YouTubeRebornPlus.bundle
          git add .
          git commit -m "Added Bundles"
          git push origin

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote Tweaks/Alderis
          git add .
          git submodule update --init --recursive --remote Tweaks/DontEatMyContent
          git add .
          git submodule update --init --recursive --remote Tweaks/FLEX
          git add .
          git submodule update --init --recursive --remote Tweaks/YTHoldForSpeed
          git add .
          git submodule update --init --recursive --remote Tweaks/PSHeader
          git add .
          git submodule update --init --recursive --remote Tweaks/Return-YouTube-Dislikes
          git add .
          git submodule update --init --recursive --remote Tweaks/YTABConfig
          git add .
          git submodule update --init --recursive --remote Tweaks/YTUHD
          git add .
          git submodule update --init --recursive --remote Tweaks/YTVideoOverlay
          git add .
          git submodule update --init --recursive --remote Tweaks/YouMute
          git add .
          git submodule update --init --recursive --remote Tweaks/YouPiP
          git add .
          git submodule update --init --recursive --remote Tweaks/YouQuality
          git add .
          git submodule update --init --recursive --remote Tweaks/YouGroupSettings
          git add .
          git submodule update --init --recursive --remote Tweaks/YouTubeHeader
          git add .
          git submodule update --init --recursive --remote Tweaks/iSponsorBlock
          git add .
          git submodule update --init --recursive
          git commit -m "updated submodules"
          git push
        continue-on-error: true

      - name: Check exit code
        run: |
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Submodule update failed with exit code $exit_code"
            exit 1
          fi
